# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 0'
    # - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm install
    - run: npm run update-readme
      # env:
      #   INSTAGRAM_USER: ${{ secrets.INSTAGRAM_USER }}
      #   INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
      #   YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    - run: |
        git config user.name John Serrano
        git config user.email andrey_201015@hotmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
        git push origin master
